const UI_I18N = {
  en: {
    tabGen:"⚡ Generate", tabSec:"🧭 Sections", tabOpt:"⚙️ Options", tabApp:"🎨 Appearance", tabBio:"📖 Bio", tabCom:"🗨️ Comments",
    btnGenerate:"⚡ Generate", imgEmptyTitle:"Ready to generate", imgEmptyHint:"Describe your character below, then press Generate",
    imgPromptLabel:"Last prompt", btnCopyPrompt:"📋 Copy Prompt", btnCopyNeg:"🚫 Copy Negative", btnVault:"🛡️ Private Vault",
    headScratch:"🗒️ Scratchpad", noteScratch:"Private notes — not used in generation.", headDesc:"📝 Description",
    btnRandom:"🎲 Random", btnClear:"🗑️ Clear", headStyle:"🎨 Art Style", StyleA:"🅰️ Primary Style", StyleB:"🅱️ Style Mix",
    Archetype:"🧍 Character Archetype", headPromptSec:"🧍 Prompt Sections", lblShow:"Show:",
    lblSubject:"🧍 Subject Details", lblEnv:"🌍 Environment / Background", lblAction:"🎬 Action / Pose", lblStyle:"✨ Style Tags", lblNeg:"🚫 Negative / Anti-Description", lblAtm:"🌫️ Global Atmosphere",
    lblLighting:"💡 Lighting", lblMood:"🎭 Mood", lblLocation:"📍 Location", lblArtist:"🎨 Artist Influence", lblCamera:"📷 Camera / Realism", lblComp:"🎞️ Compositing",
    headImgSettings:"🖼️ Image Settings", lblShape:"🖼️ Shape", lblQuantity:"🔢 Quantity", lblModel:"🤖 Model", lblSampler:"⚙️ Sampler", lblSteps:"🪜 Steps", lblGuidance:"🧭 Guidance Scale", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ Remove BG", lblSeed:"🌱 Image Seed", lblTitle:"🏷️ Image Title",
    headTheme:"🎨 Page Theme", headLang:"🌐 Language & Translate", headA11y:"♿ Accessibility",
    headBioCard:"📖 Character Bio", btnGenBio:"📖 Generate Bio", btnContBio:"➡ Continue", btnCopy:"📋 Copy", btnSpeak:"🔊 Speak",
    headCommunity:"🗨️ Community", headVault:"🛡️ Private Vault", vdTitle:"Image Details",
    headRefine:"✨ Refine Image", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Negative Prompt",
    btnRegen:"✨ Regenerate", btnCancel:"✕ Cancel", btnUsePrompt:"📋 Use Prompt", btnDownload:"⬇️ Download", btnDelete:"🗑️ Delete", btnClose:"✕ Close",
    btnRefineText:"Refine", btnSaveText:"Save", badgeView:"View", lblTranslatePrompt:"🔄 Translate Prompts to English", btnTranslate:"🔄 Translate Now",
    lblSecRegions:"Sectional Regions", lblReview:"Review translated fields. Click Apply to push them to the generator.", btnSkip:"Skip", noteChat:"Chat AI is driven from the left panel.",
    txtVaultEmpty:"Your vault is empty.<br>Generate images and save them to see them here.",
    phScratch:"Start typing your ideas here...", phDesc:"Describe your character...", phSubj:"elf, silver hair...", phEnv:"moonlit forest...", phAct:"dramatic pose...", phStyle:"masterpiece...", phNeg:"what you don't want...", phSeed:"Leave blank for random", phTitle:"Gallery display title"
  },
  es: {
    tabGen:"⚡ Generar", tabSec:"🧭 Secciones", tabOpt:"⚙️ Opciones", tabApp:"🎨 Apariencia", tabBio:"📖 Bio", tabCom:"🗨️ Comentarios",
    btnGenerate:"⚡ Generar", imgEmptyTitle:"Listo para generar", imgEmptyHint:"Describe tu personaje abajo y presiona Generar",
    imgPromptLabel:"Último prompt", btnCopyPrompt:"📋 Copiar Prompt", btnCopyNeg:"🚫 Copiar Negativo", btnVault:"🛡️ Bóveda Privada",
    headScratch:"🗒️ Bloc de notas", noteScratch:"Notas privadas — no usadas en la generación.", headDesc:"📝 Descripción",
    btnRandom:"🎲 Aleatorio", btnClear:"🗑️ Borrar", headStyle:"🎨 Estilo de Arte", StyleA:"🅰️ Estilo Principal", StyleB:"🅱️ Mezcla de Estilo",
    Archetype:"🧍 Arquetipo", headPromptSec:"🧍 Secciones de Prompt", lblShow:"Mostrar:",
    lblSubject:"🧍 Detalles del Sujeto", lblEnv:"🌍 Entorno / Fondo", lblAction:"🎬 Acción / Pose", lblStyle:"✨ Etiquetas de Estilo", lblNeg:"🚫 Negativo / Anti-Descripción", lblAtm:"🌫️ Atmósfera Global",
    lblLighting:"💡 Iluminación", lblMood:"🎭 Estado de Ánimo", lblLocation:"📍 Ubicación", lblArtist:"🎨 Influencia Artística", lblCamera:"📷 Cámara / Realismo", lblComp:"🎞️ Composición",
    headImgSettings:"🖼️ Ajustes de Imagen", lblShape:"🖼️ Forma", lblQuantity:"🔢 Cantidad", lblModel:"🤖 Modelo", lblSampler:"⚙️ Muestreador", lblSteps:"🪜 Pasos", lblGuidance:"🧭 Escala de Guía", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ Quitar Fondo", lblSeed:"🌱 Semilla", lblTitle:"🏷️ Título de Imagen",
    headTheme:"🎨 Tema de Página", headLang:"🌐 Idioma y Traducción", headA11y:"♿ Accesibilidad",
    headBioCard:"📖 Biografía del Personaje", btnGenBio:"📖 Generar Bio", btnContBio:"➡ Continuar", btnCopy:"📋 Copiar", btnSpeak:"🔊 Hablar",
    headCommunity:"🗨️ Comunidad", headVault:"🛡️ Bóveda Privada", vdTitle:"Detalles de Imagen",
    headRefine:"✨ Refinar Imagen", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Prompt Negativo",
    btnRegen:"✨ Regenerar", btnCancel:"✕ Cancelar", btnUsePrompt:"📋 Usar Prompt", btnDownload:"⬇️ Descargar", btnDelete:"🗑️ Eliminar", btnClose:"✕ Cerrar",
    btnRefineText:"Refinar", btnSaveText:"Guardar", badgeView:"Ver", lblTranslatePrompt:"🔄 Traducir Prompts al Inglés", btnTranslate:"🔄 Traducir Ahora",
    lblSecRegions:"Regiones Seccionales", lblReview:"Revisa los campos traducidos. Haz clic en Aplicar.", btnSkip:"Omitir", noteChat:"El chat AI se controla desde el panel izquierdo.",
    txtVaultEmpty:"Tu bóveda está vacía.<br>Genera y guarda imágenes para verlas aquí.",
    phScratch:"Escribe tus ideas aquí...", phDesc:"Describe tu personaje...", phSubj:"elfo, cabello plateado...", phEnv:"bosque iluminado por la luna...", phAct:"pose dramática...", phStyle:"obra maestra...", phNeg:"lo que no quieres...", phSeed:"Deja en blanco para aleatorio", phTitle:"Título de la galería"
  },
  fr: {
    tabGen:"⚡ Générer", tabSec:"🧭 Sections", tabOpt:"⚙️ Options", tabApp:"🎨 Apparence", tabBio:"📖 Bio", tabCom:"🗨️ Commentaires",
    btnGenerate:"⚡ Générer", imgEmptyTitle:"Prêt à générer", imgEmptyHint:"Décrivez votre personnage ci-dessous, puis appuyez sur Générer",
    imgPromptLabel:"Dernier prompt", btnCopyPrompt:"📋 Copier Prompt", btnCopyNeg:"🚫 Copier Négatif", btnVault:"🛡️ Coffre Privé",
    headScratch:"🗒️ Brouillon", noteScratch:"Notes privées — non utilisées pour générer.", headDesc:"📝 Description",
    btnRandom:"🎲 Aléatoire", btnClear:"🗑️ Effacer", headStyle:"🎨 Style d'Art", StyleA:"🅰️ Style Principal", StyleB:"🅱️ Mélange de Style",
    Archetype:"🧍 Archétype", headPromptSec:"🧍 Sections de Prompt", lblShow:"Afficher:",
    lblSubject:"🧍 Détails du Sujet", lblEnv:"🌍 Environnement / Fond", lblAction:"🎬 Action / Pose", lblStyle:"✨ Tags de Style", lblNeg:"🚫 Négatif / Anti-Description", lblAtm:"🌫️ Atmosphère Globale",
    lblLighting:"💡 Éclairage", lblMood:"🎭 Ambiance", lblLocation:"📍 Emplacement", lblArtist:"🎨 Influence d'Artiste", lblCamera:"📷 Caméra / Réalisme", lblComp:"🎞️ Composition",
    headImgSettings:"🖼️ Paramètres d'Image", lblShape:"🖼️ Format", lblQuantity:"🔢 Quantité", lblModel:"🤖 Modèle", lblSampler:"⚙️ Échantillonneur", lblSteps:"🪜 Étapes", lblGuidance:"🧭 Échelle de Guidage", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ Supprimer Fond", lblSeed:"🌱 Graine", lblTitle:"🏷️ Titre d'Image",
    headTheme:"🎨 Thème de Page", headLang:"🌐 Langue et Traduction", headA11y:"♿ Accessibilité",
    headBioCard:"📖 Bio du Personnage", btnGenBio:"📖 Générer Bio", btnContBio:"➡ Continuer", btnCopy:"📋 Copier", btnSpeak:"🔊 Parler",
    headCommunity:"🗨️ Communauté", headVault:"🛡️ Coffre Privé", vdTitle:"Détails de l'Image",
    headRefine:"✨ Affiner l'Image", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Prompt Négatif",
    btnRegen:"✨ Régénérer", btnCancel:"✕ Annuler", btnUsePrompt:"📋 Utiliser Prompt", btnDownload:"⬇️ Télécharger", btnDelete:"🗑️ Supprimer", btnClose:"✕ Fermer",
    btnRefineText:"Affiner", btnSaveText:"Enregistrer", badgeView:"Voir", lblTranslatePrompt:"🔄 Traduire Prompts en Anglais", btnTranslate:"🔄 Traduire",
    lblSecRegions:"Régions Sectionnelles", lblReview:"Vérifiez les champs. Cliquez sur Appliquer.", btnSkip:"Passer", noteChat:"L'IA de chat est gérée depuis le panneau gauche.",
    txtVaultEmpty:"Votre coffre est vide.<br>Générez et enregistrez des images pour les voir ici.",
    phScratch:"Notez vos idées ici...", phDesc:"Décrivez votre personnage...", phSubj:"elfe, cheveux d'argent...", phEnv:"forêt au clair de lune...", phAct:"pose dramatique...", phStyle:"chef-d'œuvre...", phNeg:"ce que vous ne voulez pas...", phSeed:"Laisser vide pour aléatoire", phTitle:"Titre de l'image"
  },
  de: {
    tabGen:"⚡ Generieren", tabSec:"🧭 Sektionen", tabOpt:"⚙️ Optionen", tabApp:"🎨 Aussehen", tabBio:"📖 Bio", tabCom:"🗨️ Kommentare",
    btnGenerate:"⚡ Generieren", imgEmptyTitle:"Bereit zur Generierung", imgEmptyHint:"Beschreibe deinen Charakter unten und drücke auf Generieren",
    imgPromptLabel:"Letzter Prompt", btnCopyPrompt:"📋 Prompt kopieren", btnCopyNeg:"🚫 Negativ kopieren", btnVault:"🛡️ Privater Tresor",
    headScratch:"🗒️ Notizblock", noteScratch:"Private Notizen — nicht für Generierung.", headDesc:"📝 Beschreibung",
    btnRandom:"🎲 Zufällig", btnClear:"🗑️ Löschen", headStyle:"🎨 Kunststil", StyleA:"🅰️ Hauptstil", StyleB:"🅱️ Stilmix",
    Archetype:"🧍 Archetyp", headPromptSec:"🧍 Prompt-Sektionen", lblShow:"Anzeigen:",
    lblSubject:"🧍 Subjektdetails", lblEnv:"🌍 Umgebung / Hintergrund", lblAction:"🎬 Aktion / Pose", lblStyle:"✨ Stil-Tags", lblNeg:"🚫 Negativ / Anti-Beschreibung", lblAtm:"🌫️ Globale Atmosphäre",
    lblLighting:"💡 Beleuchtung", lblMood:"🎭 Stimmung", lblLocation:"📍 Ort", lblArtist:"🎨 Künstler-Einfluss", lblCamera:"📷 Kamera / Realismus", lblComp:"🎞️ Komposition",
    headImgSettings:"🖼️ Bildeinstellungen", lblShape:"🖼️ Format", lblQuantity:"🔢 Menge", lblModel:"🤖 Modell", lblSampler:"⚙️ Sampler", lblSteps:"🪜 Schritte", lblGuidance:"🧭 Guidance-Skala", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ HG entfernen", lblSeed:"🌱 Seed", lblTitle:"🏷️ Bildtitel",
    headTheme:"🎨 Seitendesign", headLang:"🌐 Sprache & Übersetzung", headA11y:"♿ Barrierefreiheit",
    headBioCard:"📖 Charakter-Bio", btnGenBio:"📖 Bio generieren", btnContBio:"➡ Fortfahren", btnCopy:"📋 Kopieren", btnSpeak:"🔊 Sprechen",
    headCommunity:"🗨️ Community", headVault:"🛡️ Privater Tresor", vdTitle:"Bilddetails",
    headRefine:"✨ Bild verfeinern", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Negativ-Prompt",
    btnRegen:"✨ Regenerieren", btnCancel:"✕ Abbrechen", btnUsePrompt:"📋 Prompt nutzen", btnDownload:"⬇️ Herunterladen", btnDelete:"🗑️ Löschen", btnClose:"✕ Schließen",
    btnRefineText:"Verfeinern", btnSaveText:"Speichern", badgeView:"Ansehen", lblTranslatePrompt:"🔄 Prompts auf Englisch übersetzen", btnTranslate:"🔄 Jetzt übersetzen",
    lblSecRegions:"Sektionsbereiche", lblReview:"Überprüfe die Felder. Klicke auf Anwenden.", btnSkip:"Überspringen", noteChat:"Chat-KI wird über das linke Panel gesteuert.",
    txtVaultEmpty:"Dein Tresor ist leer.<br>Generiere und speichere Bilder, um sie hier zu sehen.",
    phScratch:"Notiere hier deine Ideen...", phDesc:"Beschreibe deinen Charakter...", phSubj:"Elf, silberne Haare...", phEnv:"Mondscheinwald...", phAct:"dramatische Pose...", phStyle:"Meisterwerk...", phNeg:"was du nicht willst...", phSeed:"Für Zufall leer lassen", phTitle:"Bildtitel"
  },
  it: {
    tabGen:"⚡ Genera", tabSec:"🧭 Sezioni", tabOpt:"⚙️ Opzioni", tabApp:"🎨 Aspetto", tabBio:"📖 Bio", tabCom:"🗨️ Commenti",
    btnGenerate:"⚡ Genera", imgEmptyTitle:"Pronto a generare", imgEmptyHint:"Descrivi il tuo personaggio qui sotto e premi Genera",
    imgPromptLabel:"Ultimo prompt", btnCopyPrompt:"📋 Copia Prompt", btnCopyNeg:"🚫 Copia Negativo", btnVault:"🛡️ Cassaforte Privata",
    headScratch:"🗒️ Blocco appunti", noteScratch:"Note private — non usate nella generazione.", headDesc:"📝 Descrizione",
    btnRandom:"🎲 Casuale", btnClear:"🗑️ Cancella", headStyle:"🎨 Stile Artistico", StyleA:"🅰️ Stile Principale", StyleB:"🅱️ Mix di Stili",
    Archetype:"🧍 Archetipo", headPromptSec:"🧍 Sezioni Prompt", lblShow:"Mostra:",
    lblSubject:"🧍 Dettagli Soggetto", lblEnv:"🌍 Ambiente / Sfondo", lblAction:"🎬 Azione / Posa", lblStyle:"✨ Tag di Stile", lblNeg:"🚫 Negativo / Anti-Descrizione", lblAtm:"🌫️ Atmosfera Globale",
    lblLighting:"💡 Illuminazione", lblMood:"🎭 Umore", lblLocation:"📍 Luogo", lblArtist:"🎨 Influenza Artistica", lblCamera:"📷 Fotocamera / Realismo", lblComp:"🎞️ Composizione",
    headImgSettings:"🖼️ Impostazioni Immagine", lblShape:"🖼️ Formato", lblQuantity:"🔢 Quantità", lblModel:"🤖 Modello", lblSampler:"⚙️ Campionatore", lblSteps:"🪜 Passi", lblGuidance:"🧭 Scala di Guida", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ Rimuovi Sfondo", lblSeed:"🌱 Seme", lblTitle:"🏷️ Titolo Immagine",
    headTheme:"🎨 Tema Pagina", headLang:"🌐 Lingua e Traduzione", headA11y:"♿ Accessibilità",
    headBioCard:"📖 Bio del Personaggio", btnGenBio:"📖 Genera Bio", btnContBio:"➡ Continua", btnCopy:"📋 Copia", btnSpeak:"🔊 Parla",
    headCommunity:"🗨️ Comunità", headVault:"🛡️ Cassaforte Privata", vdTitle:"Dettagli Immagine",
    headRefine:"✨ Affina Immagine", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Prompt Negativo",
    btnRegen:"✨ Rigenera", btnCancel:"✕ Annulla", btnUsePrompt:"📋 Usa Prompt", btnDownload:"⬇️ Scarica", btnDelete:"🗑️ Elimina", btnClose:"✕ Chiudi",
    btnRefineText:"Affina", btnSaveText:"Salva", badgeView:"Vedi", lblTranslatePrompt:"🔄 Traduci Prompt in Inglese", btnTranslate:"🔄 Traduci Ora",
    lblSecRegions:"Regioni Sezionali", lblReview:"Rivedi i campi tradotti. Clicca Applica.", btnSkip:"Salta", noteChat:"L'IA della chat è gestita dal pannello sinistro.",
    txtVaultEmpty:"La tua cassaforte è vuota.<br>Genera e salva immagini per vederle qui.",
    phScratch:"Inizia a scrivere le tue idee qui...", phDesc:"Descrivi il tuo personaggio...", phSubj:"elfo, capelli argentati...", phEnv:"foresta al chiaro di luna...", phAct:"posa drammatica...", phStyle:"capolavoro...", phNeg:"cosa non vuoi...", phSeed:"Lascia vuoto per casuale", phTitle:"Titolo galleria"
  },
  pt: {
    tabGen:"⚡ Gerar", tabSec:"🧭 Seções", tabOpt:"⚙️ Opções", tabApp:"🎨 Aparência", tabBio:"📖 Bio", tabCom:"🗨️ Comentários",
    btnGenerate:"⚡ Gerar", imgEmptyTitle:"Pronto para gerar", imgEmptyHint:"Descreva seu personagem abaixo e pressione Gerar",
    imgPromptLabel:"Último prompt", btnCopyPrompt:"📋 Copiar Prompt", btnCopyNeg:"🚫 Copiar Negativo", btnVault:"🛡️ Cofre Privado",
    headScratch:"🗒️ Rascunho", noteScratch:"Notas privadas — não usadas na geração.", headDesc:"📝 Descrição",
    btnRandom:"🎲 Aleatório", btnClear:"🗑️ Limpar", headStyle:"🎨 Estilo de Arte", StyleA:"🅰️ Estilo Principal", StyleB:"🅱️ Mistura de Estilo",
    Archetype:"🧍 Arquétipo", headPromptSec:"🧍 Seções de Prompt", lblShow:"Mostrar:",
    lblSubject:"🧍 Detalhes do Sujeito", lblEnv:"🌍 Ambiente / Fundo", lblAction:"🎬 Ação / Pose", lblStyle:"✨ Tags de Estilo", lblNeg:"🚫 Negativo / Anti-Descrição", lblAtm:"🌫️ Atmosfera Global",
    lblLighting:"💡 Iluminação", lblMood:"🎭 Humor", lblLocation:"📍 Local", lblArtist:"🎨 Influência Artística", lblCamera:"📷 Câmera / Realismo", lblComp:"🎞️ Composição",
    headImgSettings:"🖼️ Configurações de Imagem", lblShape:"🖼️ Formato", lblQuantity:"🔢 Quantidade", lblModel:"🤖 Modelo", lblSampler:"⚙️ Amostrador", lblSteps:"🪜 Passos", lblGuidance:"🧭 Escala de Guia", lblZoom:"🔎 Zoom", lblRmBg:"🖼️ Remover Fundo", lblSeed:"🌱 Semente", lblTitle:"🏷️ Título da Imagem",
    headTheme:"🎨 Tema da Página", headLang:"🌐 Idioma e Tradução", headA11y:"♿ Acessibilidade",
    headBioCard:"📖 Bio do Personagem", btnGenBio:"📖 Gerar Bio", btnContBio:"➡ Continuar", btnCopy:"📋 Copiar", btnSpeak:"🔊 Falar",
    headCommunity:"🗨️ Comunidade", headVault:"🛡️ Cofre Privado", vdTitle:"Detalhes da Imagem",
    headRefine:"✨ Refinar Imagem", lblPrompt:"📝 Prompt", lblNegPrompt:"🚫 Prompt Negativo",
    btnRegen:"✨ Regenerar", btnCancel:"✕ Cancelar", btnUsePrompt:"📋 Usar Prompt", btnDownload:"⬇️ Baixar", btnDelete:"🗑️ Excluir", btnClose:"✕ Fechar",
    btnRefineText:"Refinar", btnSaveText:"Salvar", badgeView:"Ver", lblTranslatePrompt:"🔄 Traduzir Prompts para Inglês", btnTranslate:"🔄 Traduzir Agora",
    lblSecRegions:"Regiões Seccionais", lblReview:"Revise os campos traduzidos. Clique em Aplicar.", btnSkip:"Pular", noteChat:"O chat IA é controlado pelo painel esquerdo.",
    txtVaultEmpty:"Seu cofre está vazio.<br>Gere e salve imagens para vê-las aqui.",
    phScratch:"Digite suas ideias aqui...", phDesc:"Descreva seu personagem...", phSubj:"elfo, cabelo prateado...", phEnv:"floresta enluarada...", phAct:"pose dramática...", phStyle:"obra-prima...", phNeg:"o que você não quer...", phSeed:"Deixe em branco para aleatório", phTitle:"Título da imagem"
  },
  ru: {
    tabGen:"⚡ Создать", tabSec:"🧭 Разделы", tabOpt:"⚙️ Настройки", tabApp:"🎨 Внешний вид", tabBio:"📖 Био", tabCom:"🗨️ Комментарии",
    btnGenerate:"⚡ Создать", imgEmptyTitle:"Готов к созданию", imgEmptyHint:"Опишите персонажа ниже и нажмите Создать",
    imgPromptLabel:"Последний промпт", btnCopyPrompt:"📋 Копировать Промпт", btnCopyNeg:"🚫 Копировать Негатив", btnVault:"🛡️ Личное Хранилище",
    headScratch:"🗒️ Блокнот", noteScratch:"Личные заметки — не используются при генерации.", headDesc:"📝 Описание",
    btnRandom:"🎲 Случайно", btnClear:"🗑️ Очистить", headStyle:"🎨 Стиль искусства", StyleA:"🅰️ Основной стиль", StyleB:"🅱️ Смешение стилей",
    Archetype:"🧍 Архетип", headPromptSec:"🧍 Разделы Промпта", lblShow:"Показать:",
    lblSubject:"🧍 Детали объекта", lblEnv:"🌍 Окружение / Фон", lblAction:"🎬 Действие / Поза", lblStyle:"✨ Теги стиля", lblNeg:"🚫 Негатив / Анти-описание", lblAtm:"🌫️ Общая атмосфера",
    lblLighting:"💡 Освещение", lblMood:"🎭 Настроение", lblLocation:"📍 Локация", lblArtist:"🎨 Влияние художника", lblCamera:"📷 Камера / Реализм", lblComp:"🎞️ Композиция",
    headImgSettings:"🖼️ Настройки изображения", lblShape:"🖼️ Формат", lblQuantity:"🔢 Количество", lblModel:"🤖 Модель", lblSampler:"⚙️ Сэмплер", lblSteps:"🪜 Шаги", lblGuidance:"🧭 Шкала Guidance", lblZoom:"🔎 Масштаб", lblRmBg:"🖼️ Удалить фон", lblSeed:"🌱 Сид", lblTitle:"🏷️ Название картинки",
    headTheme:"🎨 Тема страницы", headLang:"🌐 Язык и перевод", headA11y:"♿ Доступность",
    headBioCard:"📖 Био персонажа", btnGenBio:"📖 Создать Био", btnContBio:"➡ Продолжить", btnCopy:"📋 Копировать", btnSpeak:"🔊 Озвучить",
    headCommunity:"🗨️ Сообщество", headVault:"🛡️ Личное Хранилище", vdTitle:"Детали изображения",
    headRefine:"✨ Улучшить картинку", lblPrompt:"📝 Промпт", lblNegPrompt:"🚫 Негативный промпт",
    btnRegen:"✨ Пересоздать", btnCancel:"✕ Отмена", btnUsePrompt:"📋 Использовать промпт", btnDownload:"⬇️ Скачать", btnDelete:"🗑️ Удалить", btnClose:"✕ Закрыть",
    btnRefineText:"Улучшить", btnSaveText:"Сохранить", badgeView:"Смотреть", lblTranslatePrompt:"🔄 Перевести промпты на английский", btnTranslate:"🔄 Перевести сейчас",
    lblSecRegions:"Секционные области", lblReview:"Проверьте перевод. Нажмите Применить.", btnSkip:"Пропустить", noteChat:"Чат ИИ управляется с левой панели.",
    txtVaultEmpty:"Ваше хранилище пусто.<br>Создавайте и сохраняйте изображения, чтобы увидеть их здесь.",
    phScratch:"Записывайте идеи здесь...", phDesc:"Опишите вашего персонажа...", phSubj:"эльф, серебряные волосы...", phEnv:"лунный лес...", phAct:"драматичная поза...", phStyle:"шедевр...", phNeg:"то, что вы не хотите...", phSeed:"Оставьте пустым для случайного", phTitle:"Название картинки"
  },
  ja: {
    tabGen:"⚡ 生成", tabSec:"🧭 セクション", tabOpt:"⚙️ オプション", tabApp:"🎨 外観", tabBio:"📖 プロフ", tabCom:"🗨️ コメント",
    btnGenerate:"⚡ 生成", imgEmptyTitle:"生成の準備完了", imgEmptyHint:"キャラクターを説明し、生成を押してください",
    imgPromptLabel:"最後のプロンプト", btnCopyPrompt:"📋 プロンプトをコピー", btnCopyNeg:"🚫 ネガティブをコピー", btnVault:"🛡️ 保管庫",
    headScratch:"🗒️ メモ帳", noteScratch:"プライベートメモ — 生成には使用されません。", headDesc:"📝 説明",
    btnRandom:"🎲 ランダム", btnClear:"🗑️ クリア", headStyle:"🎨 アートスタイル", StyleA:"🅰️ メイン", StyleB:"🅱️ ミックス",
    Archetype:"🧍 アーキタイプ", headPromptSec:"🧍 プロンプトセクション", lblShow:"表示:",
    lblSubject:"🧍 主題の詳細", lblEnv:"🌍 環境 / 背景", lblAction:"🎬 アクション / ポーズ", lblStyle:"✨ スタイルタグ", lblNeg:"🚫 ネガティブ / 除外指定", lblAtm:"🌫️ 全体の雰囲気",
    lblLighting:"💡 照明", lblMood:"🎭 ムード", lblLocation:"📍 場所", lblArtist:"🎨 アーティストの影響", lblCamera:"📷 カメラ / リアルさ", lblComp:"🎞️ 合成効果",
    headImgSettings:"🖼️ 画像設定", lblShape:"🖼️ 形状", lblQuantity:"🔢 数量", lblModel:"🤖 モデル", lblSampler:"⚙️ サンプラー", lblSteps:"🪜 ステップ", lblGuidance:"🧭 ガイダンススケール", lblZoom:"🔎 ズーム", lblRmBg:"🖼️ 背景削除", lblSeed:"🌱 シード値", lblTitle:"🏷️ 画像タイトル",
    headTheme:"🎨 ページテーマ", headLang:"🌐 言語と翻訳", headA11y:"♿ アクセシビリティ",
    headBioCard:"📖 キャラクター経歴", btnGenBio:"📖 経歴を生成", btnContBio:"➡ 続ける", btnCopy:"📋 コピー", btnSpeak:"🔊 音声読み上げ",
    headCommunity:"🗨️ コミュニティ", headVault:"🛡️ プライベート保管庫", vdTitle:"画像の詳細",
    headRefine:"✨ 画像を調整", lblPrompt:"📝 プロンプト", lblNegPrompt:"🚫 ネガティブプロンプト",
    btnRegen:"✨ 再生成", btnCancel:"✕ キャンセル", btnUsePrompt:"📋 プロンプトを使用", btnDownload:"⬇️ ダウンロード", btnDelete:"🗑️ 削除", btnClose:"✕ 閉じる",
    btnRefineText:"調整", btnSaveText:"保存", badgeView:"表示", lblTranslatePrompt:"🔄 プロンプトを英語に翻訳", btnTranslate:"🔄 今すぐ翻訳",
    lblSecRegions:"セクション領域", lblReview:"翻訳を確認し、適用をクリックします。", btnSkip:"スキップ", noteChat:"チャットAIは左パネルで制御されます。",
    txtVaultEmpty:"保管庫は空です。<br>画像を生成して保存すると、ここに表示されます。",
    phScratch:"アイデアをここに記入...", phDesc:"キャラクターを説明してください...", phSubj:"エルフ、銀髪...", phEnv:"月明かりの森...", phAct:"ドラマチックなポーズ...", phStyle:"傑作...", phNeg:"除外したい要素...", phSeed:"ランダムにする場合は空白", phTitle:"ギャラリーのタイトル"
  },
  zh: {
    tabGen:"⚡ 生成", tabSec:"🧭 区域", tabOpt:"⚙️ 选项", tabApp:"🎨 外观", tabBio:"📖 简介", tabCom:"🗨️ 评论",
    btnGenerate:"⚡ 生成", imgEmptyTitle:"准备生成", imgEmptyHint:"在下方描述您的角色，然后点击生成",
    imgPromptLabel:"最后提示词", btnCopyPrompt:"📋 复制提示词", btnCopyNeg:"🚫 复制负面", btnVault:"🛡️ 私人金库",
    headScratch:"🗒️ 草稿本", noteScratch:"私人笔记 — 不用于生成。", headDesc:"📝 描述",
    btnRandom:"🎲 随机", btnClear:"🗑️ 清除", headStyle:"🎨 艺术风格", StyleA:"🅰️ 主要风格", StyleB:"🅱️ 混合风格",
    Archetype:"🧍 角色原型", headPromptSec:"🧍 提示词区域", lblShow:"显示:",
    lblSubject:"🧍 主体细节", lblEnv:"🌍 环境 / 背景", lblAction:"🎬 动作 / 姿势", lblStyle:"✨ 风格标签", lblNeg:"🚫 负面 / 反向描述", lblAtm:"🌫️ 全局氛围",
    lblLighting:"💡 光照", lblMood:"🎭 情绪", lblLocation:"📍 场景", lblArtist:"🎨 艺术家风格", lblCamera:"📷 相机 / 真实感", lblComp:"🎞️ 构图特效",
    headImgSettings:"🖼️ 图像设置", lblShape:"🖼️ 形状", lblQuantity:"🔢 数量", lblModel:"🤖 模型", lblSampler:"⚙️ 采样器", lblSteps:"🪜 步数", lblGuidance:"🧭 提示词引导系数", lblZoom:"🔎 缩放", lblRmBg:"🖼️ 移除背景", lblSeed:"🌱 随机种子", lblTitle:"🏷️ 图像标题",
    headTheme:"🎨 页面主题", headLang:"🌐 语言与翻译", headA11y:"♿ 无障碍",
    headBioCard:"📖 角色简介", btnGenBio:"📖 生成简介", btnContBio:"➡ 继续", btnCopy:"📋 复制", btnSpeak:"🔊 朗读",
    headCommunity:"🗨️ 社区", headVault:"🛡️ 私人金库", vdTitle:"图像详情",
    headRefine:"✨ 优化图像", lblPrompt:"📝 提示词", lblNegPrompt:"🚫 负面提示词",
    btnRegen:"✨ 重新生成", btnCancel:"✕ 取消", btnUsePrompt:"📋 使用提示词", btnDownload:"⬇️ 下载", btnDelete:"🗑️ 删除", btnClose:"✕ 关闭",
    btnRefineText:"优化", btnSaveText:"保存", badgeView:"查看", lblTranslatePrompt:"🔄 翻译提示词为英语", btnTranslate:"🔄 立即翻译",
    lblSecRegions:"区域划分", lblReview:"检查翻译字段，点击应用。", btnSkip:"跳过", noteChat:"聊天 AI 由左侧面板控制。",
    txtVaultEmpty:"您的金库是空的。<br>生成并保存图像以在此处查看。",
    phScratch:"在此处记录想法...", phDesc:"描述您的角色...", phSubj:"精灵，银发...", phEnv:"月光森林...", phAct:"戏剧性的姿势...", phStyle:"杰作...", phNeg:"您不想要的元素...", phSeed:"留空以使用随机数", phTitle:"画廊显示标题"
  }
};
